### ISSUE TITLE
Modify thermistor type in Configuration.h

### ISSUE THREAD

**Issue by jessel06** [ConfluentSpace/kossel-pro-firmware#1]
**Problem Summary**
Currently, we have an all-metal 0.4mm K-Head hotend from ZTAutomations installed (`ZT-KIT-00256(01)`) and the temp readings seem to be wrong. From prior tests, the temp is off by around -20C to -30C. This is being worked around by setting the hotend temp to 230C to compensate. 

The better solution would be to see if modifying the thermistor configured in `Marlin/Configuration.h` would give a more accurate reading.

**Comment by jessel06** [comment]
Found that none of the other thermistor settings corrected the issue. The best solution at the moment is to just buy a new known thermistor or create a custom thermistor table for the one we have.

**Comment by tsuckow** [comment]
Is the current one stable? Can you splice it to the oscope and verify its
reliable operation?

**Comment by jessel06** [comment]
It keeps a stable temp, just under temp around 20C. I'm not sure how to attach it to an oscope. From what I saw online, thermistors aren't that expensive and I'd like to see how a new known one works and compare.
